//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Project_Members = new HashSet<Project_Members>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public int Assigned_By { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Project_Members> Project_Members { get; set; }
        public virtual Project_Status Project_Status { get; set; }
        public virtual User User { get; set; }
    }
}
